name: Bot Testing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r web_requirements.txt
    
    - name: Test imports
      run: |
        python -c "from utils.logger import setup_logger; print('Logger OK')"
        python -c "from strategies.moving_average import MovingAverageStrategy; print('Strategy OK')"
    
    - name: Test bot structure
      run: |
        python -c "import bot; print('Bot module OK')"
        python -c "import web_dashboard; print('Web dashboard OK')"
